sudo: required
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y install swig; fi
    # work around https://github.com/travis-ci/travis-ci/issues/8363
  - if [ $TRAVIS_OS_NAME == linux ]; then pyenv global system 3.6; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then sudo chown -R $(whoami) /usr/local; fi
    # work around https://github.com/travis-ci/travis-ci/issues/8552
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install swig; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install python3; fi


script:
  - cmake --version
  - cmake -H. -Bbuild
  - cmake --build build --target all
  - cd build && ctest -V --output-on-failure
    #  - cmake --build build --target test
