version: '{build}'
shallow_clone: true

platform: x64
configuration: Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

matrix:
  fast_finish: true

before_build:
  - set PATH=C:\Python36-x64;%PATH%
  - bash -c "which python"
  - bash -c "python -V"
  - cmake --version
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
  - cmake --build build --config Release --target ALL_BUILD -- %MSBUILD_FLAGS%

test_script:
  - cmake --build build --config Release --target RUN_TESTS -- %MSBUILD_FLAGS%

