name: amd64 macOS .Net

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  # Building using the github runner environement directly.
  xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "Xcode" -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -v
    - name: Test
      # note: can't use the target RUN_TESTS which seems to conflict with dotnet run/test command
      #run: cmake --build build --config Release --target RUN_TESTS -v
      run: cd build && ctest -C Release --verbose --extra-verbose --output-on-failure
    - name: Install
      run: cmake --build build --config Release --target install -v
  make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v
